/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/CircleButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiPicker`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiSticker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/CircleButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/IconButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EmojiPicker`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EmojiList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EmojiSticker`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/CircleButton${`?${string}` | `#${string}` | ''}` | `/../components/IconButton${`?${string}` | `#${string}` | ''}` | `/../components/EmojiPicker${`?${string}` | `#${string}` | ''}` | `/../components/EmojiList${`?${string}` | `#${string}` | ''}` | `/../components/EmojiSticker${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/CircleButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiPicker`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EmojiSticker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
